### ISSUE TITLE
Cannot start the api server

### ISSUE THREAD

**Issue by eranmahalu** [cantrell/stable-diffusion-api-server#18] opened 2022-11-13 11:29 UTC
Hi there,
First of all, thanks for this amazing plugin! I tried to run the api server as instructed, but after going through all of the steps and trying to run the server, I get a message saying "'python3' is not recognized as an internal or external command,operable program or batch file."

Not sure I'm running it from the right directory, or did I miss anything. Can you please assist?
Thank you!

**Comment by spacewave** [comment] 2022-11-13 21:03
try just "python"  without the 3.  Seems like i can get the server to run, but photoshop can't see the server.  Turned off firewall, etc... The reality is we just want it to use Automatic1111 since we can select different models that have been trained in dreambooth, etc...

**Comment by cantrell** [comment] 2022-11-14 13:19
Yes, try `python`. (The README addresses this issue.)

@spacewave: Are you running the server on the same computer as Ps? Are you using an IP address or localhost? Did you include the port number?

I am working on A1111 support now. The problem is that it doesn't have all the APIs I need. I submitted a PR yesterday with the changes I need to be able to switch models via the API. If that gets merged, we'll be in business.

**Closed as completed by cantrell** 2022-11-14 13:19 UTC

**Comment by eranmahalu** [comment] 2022-11-14 15:46
Hi friends and thanks for your help. using python instead of python 3 helped.
Another q - will there be an uncensored version? after all we are using it locally...Thanks

**Comment by spacewave** [comment] 2022-11-15 01:23
@eranmahalu   when Christian, gets A1111 running, you will won't have to worry about settings as anything in A1111 will be available to you. 

@cantrell   Thank you for the A1111 news.  I'm on Win11.  And yes, tried, localhost, ip, ports.  I have SDHLK & A1111, both work either with localhost or IP.  When i open the api-server in a browser, it doesn't hang, not sure another way to test the api-server, in chrome-inspector?   Photoshop is set to an approved App in firewall, it fetched the Addon no problem.
